In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
from src.config.settings import CONFIG_PATH, DATA_PATH, ROOT_PATH
from src.utils.utils import collate_fn, load_yaml
import torch
import numpy as np

config = load_yaml(path=CONFIG_PATH)

# Eval

In [3]:
path_models = list(Path(config.data.training.save_dir).glob('*.pt'))

accuracy , auc, cm, recall, precision, f1, confusion_matrix = [], [], [], [], [], [], []
epochs = []

for path_model in path_models: 
    
    print(path_model)
    saved_model = torch.load(path_model)
    accuracy.append(saved_model['acc'])
    auc.append(saved_model['auc'])
    recall.append(saved_model['recall'])
    precision.append(saved_model['precision'])
    f1.append(saved_model['f1'])
    confusion_matrix.append(saved_model['confusion_matrix'])
    epochs.append(saved_model['epoch'])
    #cm.append(saved_model['confusion_matrix'])

/data/ubuntu/data/saved_models/experiment_5/model0.pt
/data/ubuntu/data/saved_models/experiment_5/model1.pt
/data/ubuntu/data/saved_models/experiment_5/model2.pt
/data/ubuntu/data/saved_models/experiment_5/model3.pt
/data/ubuntu/data/saved_models/experiment_5/model4.pt
/data/ubuntu/data/saved_models/experiment_5/model5.pt
/data/ubuntu/data/saved_models/experiment_5/model6.pt
/data/ubuntu/data/saved_models/experiment_5/model7.pt
/data/ubuntu/data/saved_models/experiment_5/model8.pt
/data/ubuntu/data/saved_models/experiment_5/model9.pt


In [4]:
confusion_matrix

[array([[41,  9],
        [10, 24]]),
 array([[45,  5],
        [10, 24]]),
 array([[45,  5],
        [ 9, 25]]),
 array([[42,  8],
        [11, 23]]),
 array([[49,  1],
        [14, 20]]),
 array([[50,  0],
        [13, 21]]),
 array([[50,  0],
        [33,  1]]),
 array([[35, 15],
        [ 5, 29]]),
 array([[37, 13],
        [ 6, 28]]),
 array([[48,  2],
        [12, 22]])]

In [5]:
import pandas as pd

df_metrics = pd.DataFrame({"accuracy":accuracy, "auc":auc, "precision":precision, 
                          "recall":recall, "f1":f1, "epoch":epochs}, index = [i.name for i in path_models]).T
df_metrics.T


accuracy       auc  precision    recall        f1  epoch
model0.pt  0.773810  0.862941   0.727273  0.705882  0.716418   44.0
model1.pt  0.821429  0.858824   0.827586  0.705882  0.761905   55.0
model2.pt  0.833333  0.878235   0.833333  0.735294  0.781250   87.0
model3.pt  0.773810  0.862941   0.741935  0.676471  0.707692   44.0
model4.pt  0.821429  0.861176   0.952381  0.588235  0.727273   64.0
model5.pt  0.845238  0.869412   1.000000  0.617647  0.763636   70.0
model6.pt  0.607143  0.886471   1.000000  0.029412  0.057143   38.0
model7.pt  0.761905  0.830588   0.659091  0.852941  0.743590   46.0
model8.pt  0.773810  0.852941   0.682927  0.823529  0.746667   47.0
model9.pt  0.833333  0.908824   0.916667  0.647059  0.758621   86.0

In [8]:
list(Path(config.data.training.save_dir).iterdir())

[PosixPath('/data/ubuntu/data/saved_models/experiment_5/model0.pt'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/model1.pt'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/model2.pt'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/model3.pt'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/model4.pt'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/model5.pt'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/model6.pt'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/model7.pt'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/model8.pt'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/model9.pt'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/config.yaml'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/experiment_5_best_model2_.csv'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_5/experiment_5_best_model9_.csv')]

In [12]:
csv_paths = list(Path(config.data.training.save_dir).glob("*.csv"))

li = []

for filename in csv_paths:
    df = pd.read_csv(filename)
    li.append(df)

frame = pd.concat(li, axis=1, ignore_index=False)
frame = frame.T.drop_duplicates().T
frame = frame.sort_values(by="ID")

mean_df = pd.DataFrame({"ID":frame.ID, "Target":frame.Target.mean(axis=1) })
#mean_df.to_csv("/data/ubuntu/data/saved_models/experiment_29/mean_all.csv", index=False)

frame.head(40)

ID    Target    Target
0     0.0  0.318184  0.263914
1     4.0  0.313956  0.309013
2    16.0  1.000000  1.000000
3    17.0  0.999999  1.000000
4    20.0  0.861404  0.310730
5    23.0  0.318784  0.304982
6    28.0  0.314233  0.226595
7    30.0  0.372016  0.295302
8    31.0  1.000000  1.000000
9    32.0  1.000000  1.000000
10   34.0  0.311882  0.255866
11   37.0  1.000000  1.000000
12   38.0  0.297307  0.271703
13   42.0  0.999252  0.999857
14   44.0  0.303543  0.277486
15   49.0  0.926004  0.298992
16   50.0  0.999943  0.999997
17   53.0  0.994385  0.999945
18   59.0  0.325658  0.240179
19   60.0  0.297646  0.281952
20   62.0  0.297082  0.284894
21   65.0  0.299088  0.272620
22   71.0  0.999646  0.999885
23   74.0  0.999992  1.000000
24   78.0  0.973155  0.314330
25   80.0  0.999541  0.999972
26   85.0  0.939106  0.281591
27   87.0  0.304325  0.320090
28   91.0  0.989850  0.238420
29   92.0  1.000000  1.000000
30   95.0  0.287076  0.318546
31   99.0  0.999998  1.000000
32  103.0  0.298581  0.337204
33  104.0  0.266259  0.247292
34  108.0  0.999999  1.000000
35  109.0  0.999693  1.000000
36  115.0  0.315970  0.264254
37  116.0  0.304421  0.298448
38  117.0  0.306108  0.295759
39  125.0  0.283194  0.225409

In [11]:
from pathlib import Path
from src.config.settings import CONFIG_PATH, DATA_PATH, ROOT_PATH
from src.utils.utils import collate_fn, load_yaml
import torch
import numpy as np

config_path = "/data/ubuntu/data/saved_models/experiment_3/config.yaml"
config = load_yaml(path=config_path)

In [17]:
import pandas as pd

df_metrics = pd.DataFrame({"accuracy":accuracy, "auc":auc, "precision":precision, 
                          "recall":recall, "f1":f1}, index = [i.name for i in path_models]).T
df_metrics.T

accuracy       auc  precision    recall        f1
model0.pt  0.666659  0.841176   0.549991  0.970560  0.701651
model1.pt  0.869037  0.968824   0.767424  0.970560  0.856628
model2.pt  0.833323  0.846471   0.916628  0.647040  0.758110
model3.pt  0.785705  0.835294   0.999938  0.470574  0.639539
model4.pt  0.785705  0.895882   0.999938  0.470574  0.639539
model5.pt  0.785705  0.832941   0.863597  0.558807  0.678070
model6.pt  0.845228  0.907059   0.999952  0.617629  0.763137

In [19]:
import pandas as pd

df_metrics = pd.DataFrame({"accuracy":accuracy, "auc":auc, "precision":precision, 
                          "recall":recall, "f1":f1}, index = [i.name for i in path_models]).T
df_metrics.T


accuracy       auc  precision    recall        f1
model0.pt  0.809514  0.885882   0.846121  0.647040  0.732818
model1.pt  0.857133  0.888824   0.999955  0.647040  0.785209
model2.pt  0.833323  0.923529   0.999950  0.588218  0.740247
model3.pt  0.869037  0.923529   0.870940  0.794094  0.830245
model4.pt  0.857133  0.934706   0.789453  0.882327  0.832812
model5.pt  0.857133  0.882353   0.999955  0.647040  0.785209
model6.pt  0.595231  0.863529   0.000000  0.000000  0.000000
model7.pt  0.797610  0.854118   0.814785  0.647040  0.720795
model8.pt  0.857133  0.904118   0.958293  0.676451  0.792591
model9.pt  0.595231  0.555294   0.000000  0.000000  0.000000

In [4]:
import pandas as pd

df_metrics = pd.DataFrame({"accuracy":accuracy, "auc":auc}, index = [i.name for i in path_models]).T
df_metrics.T


accuracy       auc
model0.pt   0.773810  0.908824
model1.pt   0.619048  0.872353
model2.pt   0.750000  0.914118
model3.pt   0.833333  0.914118
model4.pt   0.821429  0.905882
model5.pt   0.702381  0.868824
model6.pt   0.773810  0.930000
model7.pt   0.797619  0.888824
model8.pt   0.750000  0.927059
model9.pt   0.666667  0.945882
model10.pt  0.738095  0.894706
model11.pt  0.809524  0.906471
model12.pt  0.845238  0.954118
model13.pt  0.702381  0.866471
model14.pt  0.690476  0.802941
model15.pt  0.726190  0.932353
model16.pt  0.797619  0.885882
model17.pt  0.785714  0.918235
model18.pt  0.785714  0.838235
model19.pt  0.738095  0.897059
model20.pt  0.880952  0.905294
model21.pt  0.809524  0.926471
model22.pt  0.809524  0.898824
model23.pt  0.797619  0.897059
model24.pt  0.773810  0.880588
model25.pt  0.797619  0.952941
model26.pt  0.821429  0.905294
model27.pt  0.595238  0.862353
model28.pt  0.595238  0.910000
model29.pt  0.678571  0.835882

In [6]:
import pandas as pd

df_metrics = pd.DataFrame({"accuracy":accuracy, "auc":auc}, index = [i.name for i in path_models]).T
df_metrics


model0.pt  model1.pt  model2.pt  model3.pt  model4.pt  model5.pt  \
accuracy   0.803571   0.785714   0.803571   0.848214   0.821429   0.848214   
auc        0.853400   0.854063   0.864677   0.907463   0.849751   0.873300   

          model6.pt  model7.pt  model8.pt  model9.pt  model10.pt  model11.pt  \
accuracy   0.776786   0.785714   0.848214   0.785714    0.794643    0.839286   
auc        0.855390   0.869652   0.865340   0.877944    0.846434    0.902156   

          model12.pt  model13.pt  
accuracy    0.830357    0.821429  
auc         0.862023    0.876949

In [16]:
import pandas as pd

k=3
idx = (-np.asarray(auc)).argsort()[:k]
indexes = np.concatenate([np.array([0]) ,  idx])
print(df_metrics.iloc[:,idx])

csv_paths = list(Path("/data/ubuntu/data/saved_models/experiment_29/").glob("sub*.csv"))

li = []

for filename in csv_paths:
    df = pd.read_csv(filename)
    li.append(df)

frame = pd.concat(li, axis=1, ignore_index=False)
frame = frame.T.drop_duplicates().T
frame = frame.sort_values(by="ID")

frame = frame.iloc[:,indexes]

mean_df = pd.DataFrame({"ID":frame.ID, "Target":frame.Target.mean(axis=1) })
mean_df.to_csv("/data/ubuntu/data/saved_models/experiment_29/mean_all.csv", index=False)

frame

          model3.pt  model11.pt  model9.pt
accuracy   0.848214    0.839286   0.785714
auc        0.907463    0.902156   0.877944


ID    Target    Target    Target
33    0.0  0.308977  0.369084  0.262538
51    4.0  0.295342  0.372893  0.335715
40   16.0  1.000000  0.514151  1.000000
39   17.0  1.000000  0.513965  1.000000
57   20.0  0.976886  0.462409  0.344998
..    ...       ...       ...       ...
31  389.0  0.207418  0.340256  0.257769
79  391.0  0.314434  0.385984  0.260653
75  392.0  0.280937  0.314774  0.318194
59  395.0  0.337576  0.373854  0.293234
53  399.0  0.280450  0.462137  0.295454

[120 rows x 4 columns]

In [13]:
frame

ID    Target    Target    Target    Target    Target    Target  \
33    0.0  0.357355  0.372579  0.319941  0.294237  0.339035  0.336965   
51    4.0  0.322347  0.395087  0.338097  0.271006  0.413864  0.386140   
40   16.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
39   17.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
57   20.0  0.385189  0.382043  0.382536  0.986070  0.409642  0.441334   
..    ...       ...       ...       ...       ...       ...       ...   
31  389.0  0.292611  0.351041  0.304495  0.261427  0.297447  0.250010   
79  391.0  0.313193  0.392626  0.284111  0.246503  0.889148  0.343825   
75  392.0  0.290400  0.316780  0.315656  0.190226  0.265208  0.330556   
59  395.0  0.327027  0.404287  0.360869  0.287722  0.348581  0.450846   
53  399.0  0.337164  0.388138  0.405232  0.226707  0.995355  0.371839   

      Target    Target    Target    Target  
33  0.315562  0.378794  0.363297  0.325218  
51  0.402285  0.379547  0.361234  0.370889  
40  1.000000  0.999999  1.000000  1.000000  
39  0.999999  0.999982  1.000000  1.000000  
57  0.391211  0.996373  0.380170  0.931758  
..       ...       ...       ...       ...  
31  0.255749  0.325699  0.255725  0.321945  
79  0.293159  0.393196  0.285956  0.287725  
75  0.299251  0.338401  0.274983  0.260453  
59  0.381039  0.394759  0.366284  0.403528  
53  0.383136  0.995453  0.354364  0.331227  

[120 rows x 11 columns]

In [12]:
frame.to_csv("/data/ubuntu/data/saved_models/experiment_28/best1.csv", index=False)

In [6]:
print(f"AUC = {np.mean(auc)} +/- {np.std(auc)}")
print(f"ACC = {np.mean(accuracy)} +/- {np.std(accuracy)}")

AUC = 0.8677446102819237 +/- 0.02697184861881918
ACC = 0.8142857142857143 +/- 0.03009339204705841


In [13]:
import pandas as pd

k=-1
idx = (-np.asarray(auc)).argsort()[:k]
indexes = np.concatenate([np.array([0]) ,  idx+ 1])
print(df_metrics.iloc[:,idx])

csv_paths = list(Path("/data/ubuntu/data/saved_models/experiment_28/").glob("sub*.csv"))

li = []

for filename in csv_paths:
    df = pd.read_csv(filename)
    li.append(df)

frame = pd.concat(li, axis=1, ignore_index=False)
frame = frame.T.drop_duplicates().T
frame = frame.sort_values(by="ID")

frame = frame.iloc[:,indexes]

mean_df = pd.DataFrame({"ID":frame.ID, "Target":frame.Target.mean(axis=1) })
mean_df.to_csv("/data/ubuntu/data/saved_models/experiment_28/mean_4.csv", index=False)

          model1.pt  model2.pt  model0.pt  model3.pt
accuracy   0.821429   0.794643   0.794643   0.803571
auc        0.873632   0.865672   0.864013   0.832172


In [14]:
mean_df

ID    Target
33    0.0  0.327258
51    4.0  0.331281
40   16.0  1.000000
39   17.0  1.000000
57   20.0  0.677062
..    ...       ...
31  389.0  0.304017
79  391.0  0.309069
75  392.0  0.274969
59  395.0  0.374435
53  399.0  0.470762

[120 rows x 2 columns]

In [5]:
import pandas as pd

csv_paths = list(Path("/data/ubuntu/data/saved_models/experiment_27/").glob("sub*.csv"))[:3]
print(csv_paths)

li = []

for filename in csv_paths:
    df = pd.read_csv(filename)
    li.append(df)

frame = pd.concat(li, axis=1, ignore_index=False)
frame = frame.T.drop_duplicates().T
frame

[PosixPath('/data/ubuntu/data/saved_models/experiment_27/submission_model0.csv'), PosixPath('/data/ubuntu/data/saved_models/experiment_27/submission_model1.csv')]


ID    Target    Target
0    103.0  0.457050  0.402489
1    117.0  0.486045  0.386101
2     62.0  0.487977  0.345072
3    328.0  0.424411  0.312331
4    314.0  0.584355  1.000000
..     ...       ...       ...
115   91.0  0.412152  0.345833
116  330.0  0.456409  0.313811
117  324.0  0.465050  0.364219
118  318.0  0.457912  0.383363
119  126.0  0.530596  0.325746

[120 rows x 3 columns]

In [6]:
mean_df = pd.DataFrame({"ID":frame.ID, "Target":frame.Target.mean(axis=1) })
mean_df.to_csv("/data/ubuntu/data/saved_models/experiment_27/mean_2_models.csv", index=False)

In [6]:
csv_paths = list(Path("/data/ubuntu/data/saved_models/experiment_33/").glob("*.csv"))
csv_paths

[PosixPath('/data/ubuntu/data/saved_models/experiment_33/best_model3_.csv'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_33/best_model4_.csv'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_33/mean_best2__.csv'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_33/best_model12_.csv'),
 PosixPath('/data/ubuntu/data/saved_models/experiment_33/mean_best3__.csv')]

In [9]:
csv_paths = list(Path("/data/ubuntu/data/saved_models/experiment_33/").glob("best*.csv"))

li = []

for filename in csv_paths:
    df = pd.read_csv(filename)
    li.append(df)

frame = pd.concat(li, axis=1, ignore_index=False)
frame = frame.T.drop_duplicates().T
frame = frame.sort_values(by="ID")


mean_df = frame
mean_df["MEAN"] = mean_df.Target.mean(axis=1)
#mean_df = pd.DataFrame({"ID":frame.ID, "Target":frame.Target.mean(axis=1) })
#mean_df.to_csv("/data/ubuntu/data/saved_models/experiment_33/mean_best8__.csv", index=False)

mean_df.head(50)

ID    Target    Target    Target    Target    Target    Target  \
0     0.0  0.282977  0.213039  0.177168  0.224145  0.352107  0.202304   
1     4.0  0.263158  0.243765  0.796182  0.262614  0.293265  0.208303   
2    16.0  0.996024  0.999621  0.999766  0.999995  0.508742  0.999994   
3    17.0  0.991936  0.998893  0.999372  0.999979  0.508704  0.999988   
4    20.0  0.754716  0.771719  0.937918  0.971828  0.391252  0.936520   
5    23.0  0.231872  0.338154  0.641456  0.193858  0.332038  0.177558   
6    28.0  0.201947  0.233130  0.140364  0.217060  0.248711  0.162355   
7    30.0  0.221418  0.266803  0.241763  0.235345  0.269457  0.246341   
8    31.0  0.993532  0.999123  0.999315  0.999994  0.507698  0.999971   
9    32.0  0.995294  0.999840  0.999359  0.999978  0.509699  0.999985   
10   34.0  0.239988  0.213954  0.216739  0.234125  0.334137  0.214808   
11   37.0  0.987267  0.999496  0.999429  0.999943  0.508632  0.999734   
12   38.0  0.254665  0.235567  0.872966  0.834111  0.438283  0.809318   
13   42.0  0.971453  0.994627  0.989994  0.998788  0.505448  0.998773   
14   44.0  0.183238  0.315541  0.202300  0.246229  0.263479  0.206153   
15   49.0  0.247812  0.950810  0.864614  0.992193  0.383784  0.990960   
16   50.0  0.961226  0.956587  0.993165  0.999386  0.507401  0.999675   
17   53.0  0.878965  0.902047  0.926594  0.999068  0.502845  0.996134   
18   59.0  0.259875  0.225575  0.242075  0.240452  0.343975  0.166045   
19   60.0  0.232624  0.727083  0.208112  0.211020  0.287916  0.177888   
20   62.0  0.281043  0.857209  0.217096  0.957890  0.358599  0.890751   
21   65.0  0.218942  0.219243  0.165968  0.227176  0.315031  0.162069   
22   71.0  0.951065  0.992701  0.992323  0.999648  0.503982  0.999299   
23   74.0  0.987880  0.998117  0.997791  0.999777  0.506744  0.999917   
24   78.0  0.264371  0.225578  0.812318  0.881725  0.394035  0.878450   
25   80.0  0.942755  0.983505  0.960439  0.998447  0.466940  0.997500   
26   85.0  0.697672  0.247295  0.781116  0.904616  0.453901  0.952176   
27   87.0  0.266625  0.197319  0.275992  0.214998  0.299944  0.191489   
28   91.0  0.220326  0.236638  0.201129  0.775811  0.264332  0.181554   
29   92.0  0.998133  0.999864  0.999787  0.999990  0.508945  0.999997   
30   95.0  0.280959  0.799535  0.825111  0.210433  0.321022  0.215375   
31   99.0  0.993589  0.998227  0.999134  0.999915  0.508863  0.999987   
32  103.0  0.255149  0.586753  0.292369  0.934133  0.402805  0.271852   
33  104.0  0.174500  0.174513  0.166201  0.208094  0.205601  0.199378   
34  108.0  0.986676  0.999093  0.996888  0.999835  0.507627  0.999883   
35  109.0  0.966883  0.991942  0.991495  0.999181  0.507824  0.999561   
36  115.0  0.239354  0.207927  0.257374  0.170241  0.327784  0.172613   
37  116.0  0.287820  0.218001  0.851415  0.950936  0.410609  0.854390   
38  117.0  0.244268  0.266626  0.275202  0.913327  0.430990  0.217640   
39  125.0  0.268251  0.183571  0.227298  0.238428  0.319611  0.173100   
40  126.0  0.239402  0.819231  0.259499  0.944023  0.425019  0.728259   
41  127.0  0.260805  0.262499  0.290718  0.226092  0.406307  0.269813   
42  128.0  0.244963  0.230275  0.271513  0.240527  0.407421  0.225526   
43  130.0  0.224035  0.216914  0.204545  0.194006  0.272165  0.193176   
44  138.0  0.289253  0.245454  0.658662  0.223489  0.365629  0.170029   
45  142.0  0.876213  0.914933  0.976894  0.997160  0.445549  0.988046   
46  157.0  0.967811  0.989981  0.988673  0.999612  0.506558  0.998471   
47  164.0  0.227258  0.220248  0.231722  0.175738  0.311237  0.202094   
48  171.0  0.199044  0.202686  0.204430  0.161797  0.208132  0.175208   
49  181.0  0.252095  0.863195  0.274856  0.723019  0.308564  0.197253   

      Target    Target      MEAN  
0   0.190137  0.216678  0.232319  
1   0.816319  0.236653  0.390032  
2   0.999996  0.999832  0.937996  
3   0.999990  0.999779  0.937330  
4   0.823534  0.862089  0.806197  
5   0.675910  0.218282  0.351141  
6   0.215507  0.225567  0.205580  
7  