In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
from src.config.settings import CONFIG_PATH, DATA_PATH, ROOT_PATH
from src.utils.utils import collate_fn, load_yaml
import torch
import numpy as np

config = load_yaml(path=CONFIG_PATH)

/data/ubuntu/.cache/pypoetry/virtualenvs/certainty-pooling-mil-9JOr21zT-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Eval

In [3]:
path_models = list(Path(config.data.training.save_dir).glob('*.pt'))

accuracy , auc, cm = [], [], []

for path_model in path_models: 
    
    print(path_model)
    saved_model = torch.load(path_model)
    accuracy.append(saved_model['acc'])
    auc.append(saved_model['auc'])
    #cm.append(saved_model['confusion_matrix'])

/data/ubuntu/data/saved_models/experiment_31/model0.pt
/data/ubuntu/data/saved_models/experiment_31/model1.pt
/data/ubuntu/data/saved_models/experiment_31/model2.pt
/data/ubuntu/data/saved_models/experiment_31/model3.pt
/data/ubuntu/data/saved_models/experiment_31/model4.pt
/data/ubuntu/data/saved_models/experiment_31/model5.pt
/data/ubuntu/data/saved_models/experiment_31/model6.pt
/data/ubuntu/data/saved_models/experiment_31/model7.pt
/data/ubuntu/data/saved_models/experiment_31/model8.pt
/data/ubuntu/data/saved_models/experiment_31/model9.pt
/data/ubuntu/data/saved_models/experiment_31/model10.pt
/data/ubuntu/data/saved_models/experiment_31/model11.pt
/data/ubuntu/data/saved_models/experiment_31/model12.pt
/data/ubuntu/data/saved_models/experiment_31/model13.pt
/data/ubuntu/data/saved_models/experiment_31/model14.pt
/data/ubuntu/data/saved_models/experiment_31/model15.pt
/data/ubuntu/data/saved_models/experiment_31/model16.pt
/data/ubuntu/data/saved_models/experiment_31/model17.pt
/d

In [5]:
import pandas as pd

df_metrics = pd.DataFrame({"accuracy":accuracy, "auc":auc}, index = [i.name for i in path_models]).T
df_metrics.T


accuracy       auc
model0.pt   0.595238  0.845882
model1.pt   0.642857  0.888235
model2.pt   0.761905  0.897647
model3.pt   0.595238  0.853529
model4.pt   0.595238  0.928824
model5.pt   0.833333  0.874118
model6.pt   0.595238  0.926471
model7.pt   0.738095  0.853529
model8.pt   0.595238  0.880000
model9.pt   0.797619  0.889412
model10.pt  0.595238  0.918824
model11.pt  0.761905  0.848235
model12.pt  0.595238  0.875294
model13.pt  0.738095  0.859412
model14.pt  0.595238  0.822353
model15.pt  0.595238  0.807647
model16.pt  0.595238  0.875882
model17.pt  0.595238  0.811765
model18.pt  0.595238  0.871176
model19.pt  0.702381  0.826471
model20.pt  0.785714  0.834118
model21.pt  0.738095  0.841176
model22.pt  0.595238  0.946471
model23.pt  0.595238  0.851765
model24.pt  0.595238  0.876471
model25.pt  0.595238  0.601765

In [6]:
import pandas as pd

df_metrics = pd.DataFrame({"accuracy":accuracy, "auc":auc}, index = [i.name for i in path_models]).T
df_metrics


model0.pt  model1.pt  model2.pt  model3.pt  model4.pt  model5.pt  \
accuracy   0.803571   0.785714   0.803571   0.848214   0.821429   0.848214   
auc        0.853400   0.854063   0.864677   0.907463   0.849751   0.873300   

          model6.pt  model7.pt  model8.pt  model9.pt  model10.pt  model11.pt  \
accuracy   0.776786   0.785714   0.848214   0.785714    0.794643    0.839286   
auc        0.855390   0.869652   0.865340   0.877944    0.846434    0.902156   

          model12.pt  model13.pt  
accuracy    0.830357    0.821429  
auc         0.862023    0.876949

In [4]:
import pandas as pd

df_metrics = pd.DataFrame({"accuracy":accuracy, "auc":auc}, index = [i.name for i in path_models]).T
df_metrics

model0.pt  model1.pt  model2.pt  model3.pt  model4.pt  model5.pt  \
accuracy   0.794643   0.821429   0.794643   0.803571   0.785714   0.794643   
auc        0.864013   0.873632   0.865672   0.832172   0.843284   0.861692   

          model6.pt  model7.pt  model8.pt  model9.pt  
accuracy   0.857143   0.857143   0.857143   0.776786  
auc        0.915091   0.896849   0.895522   0.829519

In [4]:
import pandas as pd

df_metrics = pd.DataFrame({"accuracy":accuracy, "auc":auc}, index = [i.name for i in path_models]).T
df_metrics

model0.pt  model1.pt  model2.pt  model3.pt  model4.pt  model5.pt  \
accuracy   0.771429   0.800000   0.785714   0.871429   0.785714   0.857143   
auc        0.934524   0.841837   0.886905   0.960884   0.934099   0.868197   

          model6.pt  model7.pt  model8.pt  model9.pt  
accuracy   0.857143   0.600000   0.642857   0.814286  
auc        0.868197   0.904762   0.917517   0.896259

In [16]:
import pandas as pd

k=3
idx = (-np.asarray(auc)).argsort()[:k]
indexes = np.concatenate([np.array([0]) ,  idx])
print(df_metrics.iloc[:,idx])

csv_paths = list(Path("/data/ubuntu/data/saved_models/experiment_29/").glob("sub*.csv"))

li = []

for filename in csv_paths:
    df = pd.read_csv(filename)
    li.append(df)

frame = pd.concat(li, axis=1, ignore_index=False)
frame = frame.T.drop_duplicates().T
frame = frame.sort_values(by="ID")

frame = frame.iloc[:,indexes]

mean_df = pd.DataFrame({"ID":frame.ID, "Target":frame.Target.mean(axis=1) })
mean_df.to_csv("/data/ubuntu/data/saved_models/experiment_29/mean_all.csv", index=False)

frame

          model3.pt  model11.pt  model9.pt
accuracy   0.848214    0.839286   0.785714
auc        0.907463    0.902156   0.877944


ID    Target    Target    Target
33    0.0  0.308977  0.369084  0.262538
51    4.0  0.295342  0.372893  0.335715
40   16.0  1.000000  0.514151  1.000000
39   17.0  1.000000  0.513965  1.000000
57   20.0  0.976886  0.462409  0.344998
..    ...       ...       ...       ...
31  389.0  0.207418  0.340256  0.257769
79  391.0  0.314434  0.385984  0.260653
75  392.0  0.280937  0.314774  0.318194
59  395.0  0.337576  0.373854  0.293234
53  399.0  0.280450  0.462137  0.295454

[120 rows x 4 columns]

In [13]:
frame

ID    Target    Target    Target    Target    Target    Target  \
33    0.0  0.357355  0.372579  0.319941  0.294237  0.339035  0.336965   
51    4.0  0.322347  0.395087  0.338097  0.271006  0.413864  0.386140   
40   16.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
39   17.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
57   20.0  0.385189  0.382043  0.382536  0.986070  0.409642  0.441334   
..    ...       ...       ...       ...       ...       ...       ...   
31  389.0  0.292611  0.351041  0.304495  0.261427  0.297447  0.250010   
79  391.0  0.313193  0.392626  0.284111  0.246503  0.889148  0.343825   
75  392.0  0.290400  0.316780  0.315656  0.190226  0.265208  0.330556   
59  395.0  0.327027  0.404287  0.360869  0.287722  0.348581  0.450846   
53  399.0  0.337164  0.388138  0.405232  0.226707  0.995355  0.371839   

      Target    Target    Target    Target  
33  0.315562  0.378794  0.363297  0.325218  
51  0.402285  0.379547  0.361234  0.370889  
40  1.000000  0.999999  1.000000  1.000000  
39  0.999999  0.999982  1.000000  1.000000  
57  0.391211  0.996373  0.380170  0.931758  
..       ...       ...       ...       ...  
31  0.255749  0.325699  0.255725  0.321945  
79  0.293159  0.393196  0.285956  0.287725  
75  0.299251  0.338401  0.274983  0.260453  
59  0.381039  0.394759  0.366284  0.403528  
53  0.383136  0.995453  0.354364  0.331227  

[120 rows x 11 columns]

In [12]:
frame.to_csv("/data/ubuntu/data/saved_models/experiment_28/best1.csv", index=False)

In [6]:
print(f"AUC = {np.mean(auc)} +/- {np.std(auc)}")
print(f"ACC = {np.mean(accuracy)} +/- {np.std(accuracy)}")

AUC = 0.8677446102819237 +/- 0.02697184861881918
ACC = 0.8142857142857143 +/- 0.03009339204705841


In [13]:
import pandas as pd

k=-1
idx = (-np.asarray(auc)).argsort()[:k]
indexes = np.concatenate([np.array([0]) ,  idx+ 1])
print(df_metrics.iloc[:,idx])

csv_paths = list(Path("/data/ubuntu/data/saved_models/experiment_28/").glob("sub*.csv"))

li = []

for filename in csv_paths:
    df = pd.read_csv(filename)
    li.append(df)

frame = pd.concat(li, axis=1, ignore_index=False)
frame = frame.T.drop_duplicates().T
frame = frame.sort_values(by="ID")

frame = frame.iloc[:,indexes]

mean_df = pd.DataFrame({"ID":frame.ID, "Target":frame.Target.mean(axis=1) })
mean_df.to_csv("/data/ubuntu/data/saved_models/experiment_28/mean_4.csv", index=False)

          model1.pt  model2.pt  model0.pt  model3.pt
accuracy   0.821429   0.794643   0.794643   0.803571
auc        0.873632   0.865672   0.864013   0.832172


In [14]:
mean_df

ID    Target
33    0.0  0.327258
51    4.0  0.331281
40   16.0  1.000000
39   17.0  1.000000
57   20.0  0.677062
..    ...       ...
31  389.0  0.304017
79  391.0  0.309069
75  392.0  0.274969
59  395.0  0.374435
53  399.0  0.470762

[120 rows x 2 columns]

In [5]:
import pandas as pd

csv_paths = list(Path("/data/ubuntu/data/saved_models/experiment_27/").glob("sub*.csv"))[:3]
print(csv_paths)

li = []

for filename in csv_paths:
    df = pd.read_csv(filename)
    li.append(df)

frame = pd.concat(li, axis=1, ignore_index=False)
frame = frame.T.drop_duplicates().T
frame

[PosixPath('/data/ubuntu/data/saved_models/experiment_27/submission_model0.csv'), PosixPath('/data/ubuntu/data/saved_models/experiment_27/submission_model1.csv')]


ID    Target    Target
0    103.0  0.457050  0.402489
1    117.0  0.486045  0.386101
2     62.0  0.487977  0.345072
3    328.0  0.424411  0.312331
4    314.0  0.584355  1.000000
..     ...       ...       ...
115   91.0  0.412152  0.345833
116  330.0  0.456409  0.313811
117  324.0  0.465050  0.364219
118  318.0  0.457912  0.383363
119  126.0  0.530596  0.325746

[120 rows x 3 columns]

In [26]:
mean_df

ID    Target
0    103.0  0.423854
1    117.0  0.781928
2     62.0  0.596442
3    328.0  0.247112
4    314.0  0.999245
..     ...       ...
115   91.0  0.261611
116  330.0  0.636995
117  324.0  0.383779
118  318.0  0.686831
119  126.0  0.558887

[120 rows x 2 columns]

In [6]:
mean_df = pd.DataFrame({"ID":frame.ID, "Target":frame.Target.mean(axis=1) })
mean_df.to_csv("/data/ubuntu/data/saved_models/experiment_27/mean_2_models.csv", index=False)

# Train

In [3]:
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter
from tqdm import tqdm

from src.config.settings import CONFIG_PATH, DATA_PATH
from src.data.dataset import bag_dataset
from src.models.evaluation import evaluation
from src.models.model import Paper_network
from src.models.training import train_loop
from src.utils.utils import collate_fn, load_yaml


config = load_yaml(path=CONFIG_PATH)

metadata_file = DATA_PATH / config.data.training.metadata_file
data_root = DATA_PATH / config.data.training.data_dir

save_path = Path(config.data.training.save_dir)
save_path.mkdir(exist_ok=True)

save_model_path = save_path / config.data.training.saved_model
checkpoint_path = config.data.training.previous_model

df_annotated_bags = pd.read_csv(metadata_file)

id_train_bag, id_val_bag, target_train_bag, target_val_bag = train_test_split(
    df_annotated_bags.ID.to_list(), df_annotated_bags.Target.to_list(), test_size=config.data.split, random_state=42
)

config_tensorboard = config.data.training.tensorboard
if config_tensorboard.use_tensorboard:
    writer = SummaryWriter(config_tensorboard.tensorboard_writer)

epochs = config.data.training.epochs
lr = config.data.training.lr
batch_size = config.data.training.batch_size

train_ds = bag_dataset(id_train_bag, target_train_bag, data_root, random_selection=True)
val_ds = bag_dataset(id_val_bag, target_val_bag, data_root, random_selection=False)

train_pooling_loader = DataLoader(
    train_ds, batch_size=32, shuffle=True, num_workers=4, collate_fn=collate_fn
)
validation_pooling_loader = DataLoader(
    val_ds, batch_size=batch_size, shuffle=False, num_workers=4, collate_fn=collate_fn
)


In [40]:
minimum = 1000
target_min = -1
for batch_features, batch_targets in train_ds: 
    if batch_features.shape[0] < minimum : 
        minimum = batch_features.shape[0]
        target_min = batch_targets
    

In [41]:
minimum, target_min

(40, 0)

In [22]:
batch_features[1].shape, type(batch_features)

((128, 2048), tuple)

In [6]:
cat.shape , 128**2

(torch.Size([16296, 2048]), 16384)

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"

model = Paper_network(input_size=2048, dropout=0.5)
model = model.to(device)

criterion = torch.nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=lr)

n = config.data.training.n_monte_carlo

In [6]:
from src.models.certainty_pooling import certainty_pooling

for epoch in tqdm(range(epochs)):
    #running_loss = train_loop(train_pooling_loader, model, criterion, optimizer, epoch, device, n=n)
    
    running_loss = 0.0
    for i, sample in enumerate(train_pooling_loader, 0):
        inputs, targets = sample

        with torch.no_grad():
            inputs_pooling = np.asarray(
                [certainty_pooling(model, input, n, device, epsilon=1.0e-3) for input in inputs]
            )
        break
    break

  0%|                                                                                                                               | 0/150 [00:00<?, ?it/s]

torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([44, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])
torch.Size([128, 2048])


  0%|                                                                                                                               | 0/150 [00:02<?, ?it/s]


In [15]:
inputs_pooling.shape

(32, 2048)

In [23]:
for batch_features, batch_targets in train_pooling_loader: 
    break

T = 10

input_ = torch.cat([torch.tensor(i) for i in batch_features])
h = model(input_.to(device).float())

model.train()
cat = torch.cat([torch.tensor(i) for i in batch_features])

mc_output = torch.cat([model(cat.to(device).float()) for _ in range(T)], dim=0)
mc_output = mc_output.reshape(T,cat.shape[0],1).squeeze(-1)

output_split = torch.split(mc_output, split_size_or_sections=[i.shape[0] for i in batch_features], dim=1)
std_output = torch.cat([1 / i.std(0) for i in output_split])

z_m_global = (std_output * h.squeeze(-1))
z_m = torch.split(z_m_global, split_size_or_sections=[i.shape[0] for i in batch_features], dim=0)
k_star = torch.tensor([z_.argmax() for z_ in z_m])

pooling_input = torch.cat([torch.tensor(bag[k_star[idx]]).unsqueeze(0) for idx, bag in enumerate(batch_features)], dim=0)
pooling_target = torch.tensor(batch_targets)

TypeError: expected Tensor as element 0 in argument 0, but got int

In [17]:
pooling_input.shape

torch.Size([32, 2048])

In [97]:
z_m_global.shape , mc_output.shape

(torch.Size([4094]), torch.Size([10, 4094]))

In [68]:
output_split[0].shape , type(output_split) , h.shape

(torch.Size([10, 128]), tuple, torch.Size([3995, 1]))

In [80]:
z_m.max() , z_m.argmax()

(tensor(180.6760, device='cuda:0', grad_fn=<MaxBackward1>),
 tensor(1539, device='cuda:0'))

tensor([  38,  947,  835,  771,  914,  737, 1255,  800, 1119,  484,  378,  942,
         625,  913,  583,  241,  119,  918,   60,  538,  529,  571, 1227,  143,
          25,  373,  886,  854,  345, 1201,  561,  890])

In [65]:
std_output * h , std_output @ h

(tensor([[50.8923, 49.1789, 48.9541,  ..., 52.1460, 56.1518, 44.6217],
         [50.5437, 48.8420, 48.6187,  ..., 51.7888, 55.7671, 44.3160],
         [46.9885, 45.4065, 45.1989,  ..., 48.1460, 51.8445, 41.1989],
         ...,
         [51.3366, 49.6082, 49.3815,  ..., 52.6013, 56.6420, 45.0113],
         [50.4756, 48.7762, 48.5533,  ..., 51.7191, 55.6921, 44.2564],
         [49.2888, 47.6294, 47.4117,  ..., 50.5030, 54.3826, 43.2158]],
        device='cuda:0', grad_fn=<MulBackward0>),
 tensor([217832.3125], device='cuda:0', grad_fn=<SqueezeBackward3>))

In [75]:
(std_output * h.squeeze(-1)).shape , std_output.shape , h.shape

(torch.Size([3995]), torch.Size([3995]), torch.Size([3995, 1]))

tensor([50.8923, 48.8420, 45.1989,  ..., 52.6013, 55.6921, 43.2158],
       device='cuda:0', grad_fn=<MulBackward0>)